# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'IdCloudAccessSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for IdCloudAccessSample
  pod 'AppAuth'


end

target 'IdCloudAccessSampleUnitTests' do
  use_frameworks!
  inhibit_all_warnings!
  # Pods for testing
  pod 'AppAuth'
end
